services:
  db-optimize-logger:
    container_name: dol
    image: dol
    env_file:
      - .env
    build:
      context: ./db-optimize-logger
      args:
        INSTALL_DEV: ${INSTALL_DEV-false}
    networks:
      - ${NETWORK?Variable not set}
    volumes:
      - ./responses_output:/app/responses_output
      - ./db-optimize-logger/:/app


  vector:
    container_name: dol-vector
    image: timberio/vector:0.46.1-debian
    restart: "no"
    ports:
      - "8686:8686"
    env_file:
      - .env
    networks:
      - ${NETWORK?Variable not set}
    volumes:
      - ./responses_output:/var/log/responses_output
      - ./vector/vector.yaml:/etc/vector/vector.yaml:ro
      - ./vector/transformers:/etc/vector/transformers:ro
      - /run/user/1000/docker.sock:/var/run/docker.sock


  loki:
    container_name: dol-loki
    image: grafana/loki:main
    restart: "no"
    ports:
      - "3100:3100"
    env_file:
      - .env
    networks:
      - ${NETWORK?Variable not set}
    volumes:
      - ./loki.yaml:/etc/loki/local-config.yaml
      - loki-data:/var/lib/loki
    command: -config.file=/etc/loki/local-config.yaml


  grafana:
    extends:
      file: ./explain-dashboard-app/.config/docker-compose-base.yaml
      service: grafana
    networks:
      - ${NETWORK?Variable not set}


volumes:
  grafana-data:
    name: "dol-grafana-data"
  loki-data:
    name: "dol-loki-data"
  responses_output:

networks:
  traefik-public:
    external: true
